# Generated by Django 2.1.7 on 2019-05-05 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=260)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(blank=True, max_length=100)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('work_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('register_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addrs', models.CharField(blank=True, max_length=100)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('description', models.CharField(blank=True, max_length=260)),
            ],
        ),
        migrations.AddField(
            model_name='order_relation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Person'),
        ),
        migrations.AddField(
            model_name='food',
            name='orderby',
            field=models.ManyToManyField(through='menus.Order_relation', to='menus.Person'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Restaurant'),
        ),
    ]
