# Generated by Django 2.1.7 on 2019-05-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20190506_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_relation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_relation',
            name='totalprice',
            field=models.FloatField(default=0),
        ),
    ]
