# Generated by Django 2.1.7 on 2019-05-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20190506_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
