# Generated by Django 2.1.7 on 2019-05-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('work_id', models.CharField(max_length=20)),
                ('modify_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
